version: "3.7"

services:
    redis:
        image: redis:latest
        container_name: im-redis
        command: redis-server --requirepass 123456
        ports:
            - "6379:6379"

    mongo:
        image: mongo:latest
        container_name: im-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "123456"
        ports:
            - "27017:27017"